"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Dashboard;
const jsx_runtime_1 = require("react/jsx-runtime");
const material_1 = require("@mui/material");
const sidebar_1 = require("../../components/sidebar");
const header_1 = require("../../components/header");
const metric_card_1 = require("../../components/metric-card");
const cost_distribution_chart_1 = require("../../components/cost-distribution-chart");
const resource_distribution_1 = require("../../components/resource-distribution");
const status_card_1 = require("../../components/status-card");
const lucide_react_1 = require("lucide-react");
function Dashboard() {
    const theme = (0, material_1.useTheme)();
    return ((0, jsx_runtime_1.jsxs)(material_1.Box, { display: "flex", height: "100vh", bgcolor: theme.palette.grey[100], children: [(0, jsx_runtime_1.jsx)(sidebar_1.Sidebar, {}), (0, jsx_runtime_1.jsxs)(material_1.Box, { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden", children: [(0, jsx_runtime_1.jsx)(header_1.Header, {}), (0, jsx_runtime_1.jsxs)(material_1.Box, { component: "main", flex: 1, overflow: "auto", p: 3, children: [(0, jsx_runtime_1.jsx)(material_1.Typography, { variant: "h5", fontWeight: 600, mb: 2, children: "Resource Status" }), (0, jsx_runtime_1.jsxs)(material_1.Grid, { container: true, spacing: 3, children: [(0, jsx_runtime_1.jsxs)(material_1.Grid, { item: true, xs: 12, md: 8, children: [(0, jsx_runtime_1.jsxs)(material_1.Paper, { elevation: 3, sx: { p: 3, mb: 3 }, children: [(0, jsx_runtime_1.jsx)(material_1.Typography, { color: "textSecondary", mb: 2, children: "Cloud Provider Cost Distribution" }), (0, jsx_runtime_1.jsx)(cost_distribution_chart_1.CostDistributionChart, {})] }), (0, jsx_runtime_1.jsxs)(material_1.Paper, { elevation: 3, sx: { p: 3, mb: 3 }, children: [(0, jsx_runtime_1.jsx)(material_1.Typography, { color: "textSecondary", mb: 2, children: "Service Status" }), (0, jsx_runtime_1.jsx)(status_card_1.StatusCard, {})] })] }), (0, jsx_runtime_1.jsxs)(material_1.Grid, { item: true, xs: 12, md: 4, children: [(0, jsx_runtime_1.jsxs)(material_1.Paper, { elevation: 3, sx: { p: 3, mb: 3 }, children: [(0, jsx_runtime_1.jsx)(material_1.Typography, { color: "textSecondary", mb: 2, children: "Active resources by type" }), (0, jsx_runtime_1.jsx)(resource_distribution_1.ResourceDistribution, {})] }), (0, jsx_runtime_1.jsxs)(material_1.Paper, { elevation: 3, sx: {
                                                    p: 2,
                                                    bgcolor: '#1e1e2f',
                                                    color: '#fff',
                                                    fontFamily: 'monospace',
                                                }, children: [(0, jsx_runtime_1.jsx)(material_1.Typography, { variant: "subtitle2", mb: 1, children: "\u25B8 System Logs" }), (0, jsx_runtime_1.jsx)(material_1.Divider, { sx: { bgcolor: '#444', mb: 1 } }), (0, jsx_runtime_1.jsxs)(material_1.Box, { component: "pre", sx: { m: 0, whiteSpace: 'pre-wrap' }, children: ["[INFO] System initialized", '\n', "[LOAD] Loading resources from AWS region us-east-1", '\n', "[LOAD] Loading resources from Azure West US", '\n', "[WARN] High CPU usage detected on instance i-0123456789", '\n', "[INFO] Auto-scaling group triggered", '\n', "[LOAD] Loading resources from GCP us-central1", '\n', "[INFO] All resources loaded successfully"] })] })] }), (0, jsx_runtime_1.jsx)(material_1.Grid, { item: true, xs: 12, children: (0, jsx_runtime_1.jsxs)(material_1.Grid, { container: true, spacing: 2, children: [(0, jsx_runtime_1.jsx)(material_1.Grid, { item: true, xs: 12, sm: 6, md: 3, children: (0, jsx_runtime_1.jsx)(metric_card_1.MetricCard, { title: "CPU Usage", value: "78%", change: "+2.5% from last month", changeType: "positive", icon: lucide_react_1.Cpu, color: "blue" }) }), (0, jsx_runtime_1.jsx)(material_1.Grid, { item: true, xs: 12, sm: 6, md: 3, children: (0, jsx_runtime_1.jsx)(metric_card_1.MetricCard, { title: "Storage Used", value: "1.2 TB", change: "+50GB from last month", changeType: "neutral", icon: lucide_react_1.HardDrive, color: "purple" }) }), (0, jsx_runtime_1.jsx)(material_1.Grid, { item: true, xs: 12, sm: 6, md: 3, children: (0, jsx_runtime_1.jsx)(metric_card_1.MetricCard, { title: "Active Resources", value: "284", change: "+12 new resources", changeType: "positive", icon: lucide_react_1.Activity, color: "cyan" }) }), (0, jsx_runtime_1.jsx)(material_1.Grid, { item: true, xs: 12, sm: 6, md: 3, children: (0, jsx_runtime_1.jsx)(metric_card_1.MetricCard, { title: "Total Cost", value: "$13,500", change: "+8% from last month", changeType: "negative", icon: lucide_react_1.DollarSign, color: "teal" }) })] }) })] })] })] })] }));
}
//# sourceMappingURL=dashboard.js.map