import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Grid, Typography, Paper, useTheme, Divider, } from '@mui/material';
import { Sidebar } from '../../components/sidebar';
import { Header } from '../../components/header';
import { MetricCard } from '../../components/metric-card';
import { CostDistributionChart } from '../../components/cost-distribution-chart';
import { ResourceDistribution } from '../../components/resource-distribution';
import { StatusCard } from '../../components/status-card';
import { Cpu, HardDrive, Activity, DollarSign } from 'lucide-react';
export default function Dashboard() {
    const theme = useTheme();
    return (_jsxs(Box, { display: "flex", height: "100vh", bgcolor: theme.palette.grey[100], children: [_jsx(Sidebar, {}), _jsxs(Box, { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden", children: [_jsx(Header, {}), _jsxs(Box, { component: "main", flex: 1, overflow: "auto", p: 3, children: [_jsx(Typography, { variant: "h5", fontWeight: 600, mb: 2, children: "Resource Status" }), _jsxs(Grid, { container: true, spacing: 3, children: [_jsxs(Grid, { item: true, xs: 12, md: 8, children: [_jsxs(Paper, { elevation: 3, sx: { p: 3, mb: 3 }, children: [_jsx(Typography, { color: "textSecondary", mb: 2, children: "Cloud Provider Cost Distribution" }), _jsx(CostDistributionChart, {})] }), _jsxs(Paper, { elevation: 3, sx: { p: 3, mb: 3 }, children: [_jsx(Typography, { color: "textSecondary", mb: 2, children: "Service Status" }), _jsx(StatusCard, {})] })] }), _jsxs(Grid, { item: true, xs: 12, md: 4, children: [_jsxs(Paper, { elevation: 3, sx: { p: 3, mb: 3 }, children: [_jsx(Typography, { color: "textSecondary", mb: 2, children: "Active resources by type" }), _jsx(ResourceDistribution, {})] }), _jsxs(Paper, { elevation: 3, sx: {
                                                    p: 2,
                                                    bgcolor: '#1e1e2f',
                                                    color: '#fff',
                                                    fontFamily: 'monospace',
                                                }, children: [_jsx(Typography, { variant: "subtitle2", mb: 1, children: "\u25B8 System Logs" }), _jsx(Divider, { sx: { bgcolor: '#444', mb: 1 } }), _jsxs(Box, { component: "pre", sx: { m: 0, whiteSpace: 'pre-wrap' }, children: ["[INFO] System initialized", '\n', "[LOAD] Loading resources from AWS region us-east-1", '\n', "[LOAD] Loading resources from Azure West US", '\n', "[WARN] High CPU usage detected on instance i-0123456789", '\n', "[INFO] Auto-scaling group triggered", '\n', "[LOAD] Loading resources from GCP us-central1", '\n', "[INFO] All resources loaded successfully"] })] })] }), _jsx(Grid, { item: true, xs: 12, children: _jsxs(Grid, { container: true, spacing: 2, children: [_jsx(Grid, { item: true, xs: 12, sm: 6, md: 3, children: _jsx(MetricCard, { title: "CPU Usage", value: "78%", change: "+2.5% from last month", changeType: "positive", icon: Cpu, color: "blue" }) }), _jsx(Grid, { item: true, xs: 12, sm: 6, md: 3, children: _jsx(MetricCard, { title: "Storage Used", value: "1.2 TB", change: "+50GB from last month", changeType: "neutral", icon: HardDrive, color: "purple" }) }), _jsx(Grid, { item: true, xs: 12, sm: 6, md: 3, children: _jsx(MetricCard, { title: "Active Resources", value: "284", change: "+12 new resources", changeType: "positive", icon: Activity, color: "cyan" }) }), _jsx(Grid, { item: true, xs: 12, sm: 6, md: 3, children: _jsx(MetricCard, { title: "Total Cost", value: "$13,500", change: "+8% from last month", changeType: "negative", icon: DollarSign, color: "teal" }) })] }) })] })] })] })] }));
}
//# sourceMappingURL=dashboard.js.map